torch_settings:
  device: cpu

behaviors:
  BattleBot:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 1000
    max_steps: 20000000
    checkpoint_interval: 200000
    time_horizon: 64
    summary_freq: 10000
    
    self_play:
      save_steps: 20000
      team_change: 100000
      swap_steps: 10000
      window: 10
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0

environment_parameters:
  spawn_area_frac:
    curriculum:
      - name: Close
        completion_criteria:
          measure: progress
          behavior: BattleBot
          threshold: 0.025
          min_lesson_length: 100
          signal_smoothing: true
          require_reset: true
        value: 0.20
      - name: Medium
        completion_criteria:
          measure: progress
          behavior: BattleBot
          threshold: 0.075
          min_lesson_length: 100
          signal_smoothing: true
          require_reset: true
        value: 0.60
      - name: Full
        value: 1.0